name: Deploy Frontend Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies & Build
        run: |
          npm install
          npm run build

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy dist folder via rsync with password
        env:
          SSH_PASSWORD: ${{ secrets.DCISM_PASSWORD }}
        run: |
          # Use rsync + sshpass to copy files with password
          sshpass -p "$SSH_PASSWORD" rsync -avz -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }}" ./dist/ ${{ secrets.DCISM_EMAIL }}@${{ secrets.DCISM_HOST }}:/home/username/${{ secrets.DCISM_DOMAIN }}/
